name: perfos
description: Application de calcul de performances de décollage et atterrissage.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # requis pour certaines versions
  min_sdk_ios: 10 # requis pour certaines versions
  # --- Partie spécifique pour Android Adaptatif ---
  adaptive_icon_background: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/icon.png"
