import 'package:flutter/material.dart';

class ChecklistSection {
  final String title;
  final List<ChecklistItem> items;
  ChecklistSection({required this.title, required this.items});
}

class ChecklistItem {
  final String action;
  final String status;
  final bool isCheckable;
  final Color? color; // Nouveau : permet de définir une couleur spécifique
  
  ChecklistItem({
    required this.action, 
    required this.status, 
    this.isCheckable = true,
    this.color,
  });
}

final Map<String, List<ChecklistSection>> aircraftChecklists = {
  'F-GYKX': [
    ChecklistSection(title: 'AVANT MISE EN ROUTE', items: [
      ChecklistItem(action: 'ATIS (par téléphone ou radio)', status: 'notée'),
      ChecklistItem(action: 'Verrière', status: 'fermée'),
      ChecklistItem(action: 'Frein de parc', status: 'serré'),
      ChecklistItem(action: 'Sièges', status: 'réglés, verrouillés'),
      ChecklistItem(action: 'Ceintures et harnais', status: 'attachés'),
      ChecklistItem(action: 'Commandes de vol', status: 'libres'),
      ChecklistItem(action: 'Radio MASTER', status: 'OFF'),
      ChecklistItem(action: 'Robinet essence', status: 'ouvert', color: Colors.red),
      ChecklistItem(action: 'Jaugeur essence et autonomie', status: 'vérifié'),
      ChecklistItem(action: 'Horamètre', status: 'noté'),
      ChecklistItem(action: 'Volets', status: 'rentrés'),
    ]),
    ChecklistSection(title: 'DÉMARRAGE DU MOTEUR', items: [
      ChecklistItem(action: 'Interrupteur batterie', status: 'ON'),
      ChecklistItem(action: 'Réchauffage carburateur', status: 'froid (pousser)'),
      ChecklistItem(action: 'Mixture', status: 'plein riche (vers le haut)'),
      ChecklistItem(action: 'Feu anti-collision', status: 'ON'),
      ChecklistItem(action: 'Sélecteur magnétos', status: 'position L (LEFT)'),
      ChecklistItem(action: 'Pompe électrique', status: 'ON'),
      ChecklistItem(action: 'Manette des gaz', status: '3 injections puis 1/4 en avant'),
      ChecklistItem(action: 'Zone hélice', status: 'dégagée', color: Colors.red),
      ChecklistItem(action: 'Démarreur', status: 'marche (15 à 20 sec max)'),
    ]),
    ChecklistSection(title: 'APRÈS MISE EN ROUTE', items: [
      ChecklistItem(action: 'Pression d’huile (20s max)', status: 'plage verte', color: Colors.red),
      ChecklistItem(action: 'Sélecteur magnétos', status: 'L+R (Both)', color: Colors.orange),
      ChecklistItem(action: 'Régime', status: '1200 tr/min'),
      ChecklistItem(action: 'Alternateur', status: 'ON'),
      ChecklistItem(action: 'Voltmètre', status: 'plage verte'),
      ChecklistItem(action: 'Pompe électrique', status: 'OFF'),
      ChecklistItem(action: 'Pression d’essence', status: 'plage verte'),
      ChecklistItem(action: 'Radio MASTER', status: 'ON'),
      ChecklistItem(action: 'Fréquences et transpondeur (GND)', status: 'réglés'),
      ChecklistItem(action: 'Voyants', status: 'testés'),
      ChecklistItem(action: 'Altimètre', status: 'réglé QNH'),
      ChecklistItem(action: 'Indicateur de dépression', status: 'vérifié'),
      ChecklistItem(action: 'Horizon artificiel', status: 'vérifié'),
      ChecklistItem(action: 'Heure bloc', status: 'notée'),
    ]),
    ChecklistSection(title: 'DÉBUT DU ROULAGE', items: [
      ChecklistItem(action: 'Phares', status: 'ON'),
      ChecklistItem(action: 'Frein de parc', status: 'desserré'),
      ChecklistItem(action: 'Freins', status: 'essayés et symétriques', color: Colors.orange),
      ChecklistItem(action: 'Gyroscopes et bille', status: 'vérifiés'),
      ChecklistItem(action: 'ATTENTION', status: 'Éviter de dépasser 1200 tr/min tant que la température d’huile reste en plage jaune', isCheckable: false, color: Colors.orange),
    ]),
    ChecklistSection(title: 'POINT FIXE', items: [
      ChecklistItem(action: 'Frein de parc', status: 'serré'),
      ChecklistItem(action: 'Pression et température d’huile', status: 'plage verte'),
      ChecklistItem(action: 'Pression d’essence', status: 'plage verte'),
      ChecklistItem(action: 'Mixture', status: 'plein riche (vers le haut)'),
      ChecklistItem(action: 'Réchauffage carburateur', status: 'froid (pousser)'),
      ChecklistItem(action: 'Vérification magnétos (2000 tr/min)', status: 'L ou R vs L+R (max 175) / L vs R (max 50)'),
      ChecklistItem(action: 'Réchauffage carburateur', status: 'chaud (tirer) -> Chute ~100 tr/min'),
      ChecklistItem(action: 'Vérification mixture', status: 'Appauvrir -> Chute -> Plein riche'),
      ChecklistItem(action: 'Vérification ralenti', status: '600 à 850 tr/min'),
      ChecklistItem(action: 'Gaz', status: '1200 tr/min'),
    ]),
    ChecklistSection(title: 'AVANT DÉCOLLAGE', items: [
      ChecklistItem(action: 'Commandes', status: 'libres', color: Colors.red),
      ChecklistItem(action: 'Sélecteur magnétos', status: 'L+R (Both)', color: Colors.red),
      ChecklistItem(action: 'Cabine (sièges, ceintures)', status: 'vérifiée'),
      ChecklistItem(action: 'Verrière', status: 'fermée, verrouillée', color: Colors.red),
      ChecklistItem(action: 'Robinet essence', status: 'ouvert', color: Colors.red),
      ChecklistItem(action: 'Pompe électrique', status: 'ON'),
      ChecklistItem(action: 'Trim de profondeur', status: 'position décollage', color: Colors.red),
      ChecklistItem(action: 'Instruments moteur', status: 'plages vertes'),
      ChecklistItem(action: 'Volets', status: 'plein sortis, puis 1er cran', color: Colors.orange),
      ChecklistItem(action: 'Conservateur de cap', status: 'réglé'),
      ChecklistItem(action: 'Transpondeur', status: 'ALT'),
      ChecklistItem(action: 'Voyants alarmes', status: 'éteints'),
    ]),
    ChecklistSection(title: 'BRIEFING AVANT DÉCOLLAGE', items: [
      ChecklistItem(action: 'Briefing', status: 'Je décolle piste ……… vitesse de rotation 100 km/h', isCheckable: false),
      ChecklistItem(action: 'Panne < Rot', status: 'tout réduit, je freine dans l’axe, je dégage', isCheckable: false, color: Colors.red),
      ChecklistItem(action: 'Panne mineure', status: 'tour de piste adapté pour revenir me poser', isCheckable: false),
      ChecklistItem(action: 'Panne majeure', status: 'manche avant, vitesse 135 km/h, devant (secteur 30°)', isCheckable: false, color: Colors.red),
      ChecklistItem(action: 'Confirmer briefing', status: 'Fait'),
    ]),
    ChecklistSection(title: 'BRIEFING ARRIVÉE', items: [
      ChecklistItem(action: 'Aérodrome', status: 'toujours accessible (ATIS ou visuel)', isCheckable: false),
      ChecklistItem(action: 'Radio', status: 'Contact 3 min avant point entrée ou verticale', isCheckable: false),
      ChecklistItem(action: 'TDP', status: 'Altitude du tour de piste ______ ft', isCheckable: false),
      ChecklistItem(action: 'Confirmer briefing', status: 'Fait'),
    ]),
    ChecklistSection(title: 'APRÈS ATTERRISSAGE', items: [
      ChecklistItem(action: 'Pompe électrique', status: 'OFF'),
      ChecklistItem(action: 'Volets', status: 'rentrés'),
      ChecklistItem(action: 'Transpondeur', status: 'GND'),
    ]),
    ChecklistSection(title: 'ARRÊT MOTEUR', items: [
      ChecklistItem(action: 'Frein de parc', status: 'serré'),
      ChecklistItem(action: 'Radio MASTER', status: 'OFF'),
      ChecklistItem(action: 'Phares et feux de nav', status: 'OFF (sauf anti-col)'),
      ChecklistItem(action: 'Essai coupure au ralenti', status: 'vérifié'),
      ChecklistItem(action: 'Régime', status: '1000 tr/min'),
      ChecklistItem(action: 'Mixture', status: 'étouffoir (bas)', color: Colors.red),
      ChecklistItem(action: 'Magnétos / Clés', status: 'OFF / retirées', color: Colors.red),
      ChecklistItem(action: 'Alternateur / Batterie', status: 'OFF'),
      ChecklistItem(action: 'Horamètre / Heure bloc', status: 'notés'),
      ChecklistItem(action: 'Volets', status: 'Sortis (2e cran)'),
      ChecklistItem(action: 'Frein de parc', status: 'desserré (si possible)'),
    ]),
  ],
  'F-BVCY': [
    ChecklistSection(title: 'AVANT MISE EN ROUTE', items: [
      ChecklistItem(action: 'ATIS (par téléphone ou radio)', status: 'notée'),
      ChecklistItem(action: 'Verrière', status: 'fermée'),
      ChecklistItem(action: 'Frein de parc', status: 'serré'),
      ChecklistItem(action: 'Sièges', status: 'réglés, verrouillés'),
      ChecklistItem(action: 'Ceintures', status: 'attachés'),
      ChecklistItem(action: 'Commandes de vol', status: 'libres'),
      ChecklistItem(action: 'Radio et transpondeur', status: 'OFF'),
      ChecklistItem(action: 'Robinet essence', status: 'ouvert', color: Colors.red),
      ChecklistItem(action: 'Jaugeur essence et autonomie', status: 'vérifié'),
      ChecklistItem(action: 'Horamètre', status: 'noté'),
      ChecklistItem(action: 'Volets', status: 'rentrés'),
    ]),
    ChecklistSection(title: 'DÉMARRAGE DU MOTEUR', items: [
      ChecklistItem(action: 'Interrupteur batterie', status: 'ON'),
      ChecklistItem(action: 'Réchauffage carburateur', status: 'froid (pousser)'),
      ChecklistItem(action: 'Mixture', status: 'plein riche (POUSSER)'),
      ChecklistItem(action: 'Feu anti-collision', status: 'ON'),
      ChecklistItem(action: 'Sélecteur magnétos', status: 'position L (LEFT)'),
      ChecklistItem(action: 'Pompe électrique', status: 'ON'),
      ChecklistItem(action: 'Manette des gaz', status: '3 injections puis 1/4 en avant'),
      ChecklistItem(action: 'Zone hélice', status: 'dégagée', color: Colors.red),
      ChecklistItem(action: 'Démarreur', status: 'marche (15 à 20 sec max)'),
    ]),
    ChecklistSection(title: 'APRÈS MISE EN ROUTE', items: [
      ChecklistItem(action: 'Pression d’huile (20s max)', status: 'plage verte', color: Colors.red),
      ChecklistItem(action: 'Sélecteur magnétos', status: 'L+R (Both)', color: Colors.orange),
      ChecklistItem(action: 'Régime', status: '1200 tr/min'),
      ChecklistItem(action: 'Alternateur', status: 'ON'),
      ChecklistItem(action: 'Voltmètre', status: 'charge vérifiée (+)'),
      ChecklistItem(action: 'Pompe électrique', status: 'OFF'),
      ChecklistItem(action: 'Pression d’essence', status: 'voyant éteint'),
      ChecklistItem(action: 'Radio', status: 'ON'),
      ChecklistItem(action: 'Fréquences et transpondeur (GND)', status: 'réglés'),
      ChecklistItem(action: 'Voyants', status: 'éteints'),
      ChecklistItem(action: 'Altimètre', status: 'réglé QNH'),
      ChecklistItem(action: 'Indicateur de dépression', status: 'vérifié'),
      ChecklistItem(action: 'Horizon artificiel', status: 'vérifié'),
      ChecklistItem(action: 'Heure bloc', status: 'notée'),
    ]),
    ChecklistSection(title: 'DÉBUT DU ROULAGE', items: [
      ChecklistItem(action: 'Phares', status: 'ON'),
      ChecklistItem(action: 'Frein de parc', status: 'desserré'),
      ChecklistItem(action: 'Freins', status: 'essayés et symétriques', color: Colors.orange),
      ChecklistItem(action: 'Gyroscopes et bille', status: 'vérifiés'),
      ChecklistItem(action: 'ATTENTION', status: 'Éviter de dépasser 1200 tr/min (T° huile jaune)', isCheckable: false, color: Colors.orange),
    ]),
    ChecklistSection(title: 'POINT FIXE', items: [
      ChecklistItem(action: 'Frein de parc', status: 'serré'),
      ChecklistItem(action: 'Pression et température d’huile', status: 'plage verte'),
      ChecklistItem(action: 'Pression d’essence', status: 'voyant éteint'),
      ChecklistItem(action: 'Mixture', status: 'plein riche (POUSSER)'),
      ChecklistItem(action: 'Réchauffage carburateur', status: 'froid (pousser)'),
      ChecklistItem(action: 'Vérification magnétos (1800 tr/min)', status: 'Chute max 125, écart max 50'),
      ChecklistItem(action: 'Réchauffage carburateur', status: 'chaud (tirer) -> Chute ~100 tr/min'),
      ChecklistItem(action: 'Vérification mixture', status: 'Appauvrir -> Chute -> Plein riche'),
      ChecklistItem(action: 'Vérification ralenti', status: '600 à 850 tr/min'),
      ChecklistItem(action: 'Gaz', status: '1200 tr/min'),
    ]),
    ChecklistSection(title: 'AVANT DÉCOLLAGE', items: [
      ChecklistItem(action: 'Commandes', status: 'libres', color: Colors.red),
      ChecklistItem(action: 'Sélecteur magnétos', status: 'L+R (Both)', color: Colors.red),
      ChecklistItem(action: 'Cabine (sièges, ceintures)', status: 'vérifiée'),
      ChecklistItem(action: 'Verrière', status: 'fermée, verrouillée', color: Colors.red),
      ChecklistItem(action: 'Robinet essence', status: 'ouvert', color: Colors.red),
      ChecklistItem(action: 'Pompe électrique', status: 'ON'),
      ChecklistItem(action: 'Trim de profondeur', status: 'position décollage', color: Colors.red),
      ChecklistItem(action: 'Instruments moteur', status: 'plages vertes'),
      ChecklistItem(action: 'Volets', status: 'plein sortis, puis 1er cran', color: Colors.orange),
      ChecklistItem(action: 'Conservateur de cap', status: 'réglé'),
      ChecklistItem(action: 'Transpondeur', status: 'ALT'),
      ChecklistItem(action: 'Voyants alarmes', status: 'éteints'),
    ]),
    ChecklistSection(title: 'BRIEFING AVANT DÉCOLLAGE', items: [
      ChecklistItem(action: 'Rotation', status: '100 km/h', isCheckable: false),
      ChecklistItem(action: 'Panne < Rot', status: 'tout réduit, je freine dans l’axe, je dégage', isCheckable: false, color: Colors.red),
      ChecklistItem(action: 'Panne mineure', status: 'tour de piste adapté pour revenir me poser', isCheckable: false),
      ChecklistItem(action: 'Panne majeure', status: 'manche avant, vitesse 135 km/h, devant (30°)', isCheckable: false, color: Colors.red),
      ChecklistItem(action: 'Confirmer briefing', status: 'Fait'),
    ]),
    ChecklistSection(title: 'APRÈS ATTERRISSAGE', items: [
      ChecklistItem(action: 'Pompe électrique', status: 'OFF'),
      ChecklistItem(action: 'Volets', status: 'rentrés'),
      ChecklistItem(action: 'Transpondeur', status: 'GND'),
    ]),
    ChecklistSection(title: 'ARRÊT MOTEUR', items: [
      ChecklistItem(action: 'Frein de parc', status: 'serré'),
      ChecklistItem(action: 'Radio et transpondeur', status: 'OFF'),
      ChecklistItem(action: 'Phares et feux de nav', status: 'OFF (sauf anti-col)'),
      ChecklistItem(action: 'Essai coupure au ralenti', status: 'vérifié'),
      ChecklistItem(action: 'Régime', status: '1000 tr/min'),
      ChecklistItem(action: 'Mixture', status: 'étouffoir (TIRER)', color: Colors.red),
      ChecklistItem(action: 'Magnétos / Clés', status: 'OFF / retirées', color: Colors.red),
      ChecklistItem(action: 'Alternateur / Batterie', status: 'OFF'),
      ChecklistItem(action: 'Volets', status: 'Sortis (2e cran)'),
      ChecklistItem(action: 'Frein de parc', status: 'desserré (si possible)'),
    ]),
  ],
  'F-HAIX': [
    ChecklistSection(title: 'AVANT MISE EN ROUTE', items: [
      ChecklistItem(action: 'Horamètre', status: 'noté'),
      ChecklistItem(action: 'ATIS (par téléphone ou radio)', status: 'notée'),
      ChecklistItem(action: 'Verrière', status: 'fermée'),
      ChecklistItem(action: 'Frein de parc', status: 'serré'),
      ChecklistItem(action: 'Sièges', status: 'réglés, verrouillés'),
      ChecklistItem(action: 'Ceintures et harnais', status: 'attachés'),
      ChecklistItem(action: 'Commandes de vol', status: 'libres'),
      ChecklistItem(action: 'Radio MASTER', status: 'OFF'),
      ChecklistItem(action: 'Robinet essence', status: 'le moins plein, ouvert', color: Colors.red),
      ChecklistItem(action: 'Jaugeurs essence et autonomie (G, C, D)', status: 'vérifié'),
      ChecklistItem(action: 'Volets', status: 'rentrés'),
    ]),
    ChecklistSection(title: 'DÉMARRAGE DU MOTEUR', items: [
      ChecklistItem(action: 'Interrupteur batterie', status: 'ON'),
      ChecklistItem(action: 'Réchauffage carburateur', status: 'froid (pousser)'),
      ChecklistItem(action: 'Mixture', status: 'plein riche (vers le haut)'),
      ChecklistItem(action: 'Feu anti-collision', status: 'ON'),
      ChecklistItem(action: 'Sélecteur magnétos', status: 'position L (LEFT)'),
      ChecklistItem(action: 'Pompe électrique', status: 'ON'),
      ChecklistItem(action: 'Manette des gaz', status: '3 injections puis 1/4 en avant'),
      ChecklistItem(action: 'Zone hélice', status: 'dégagée', color: Colors.red),
      ChecklistItem(action: 'Démarreur', status: 'marche (15 à 20 sec max)'),
    ]),
    ChecklistSection(title: 'APRÈS MISE EN ROUTE', items: [
      ChecklistItem(action: 'Pression d’huile (20s max)', status: 'plage verte', color: Colors.red),
      ChecklistItem(action: 'Sélecteur magnétos', status: 'L+R (Both)', color: Colors.orange),
      ChecklistItem(action: 'Régime', status: '1200 tr/min'),
      ChecklistItem(action: 'Alternateur', status: 'ON'),
      ChecklistItem(action: 'Voltmètre', status: 'plage verte'),
      ChecklistItem(action: 'Robinet essence', status: 'le plus plein, ouvert', color: Colors.orange),
      ChecklistItem(action: 'Pompe électrique', status: 'OFF'),
      ChecklistItem(action: 'Pression d’essence', status: 'plage verte'),
      ChecklistItem(action: 'Radio MASTER', status: 'ON'),
      ChecklistItem(action: 'Fréquences et transpondeur (GND)', status: 'réglés'),
      ChecklistItem(action: 'Voyants', status: 'testés'),
      ChecklistItem(action: 'Altimètre', status: 'réglé QNH'),
      ChecklistItem(action: 'Indicateur de dépression', status: 'vérifié'),
      ChecklistItem(action: 'Horizon artificiel', status: 'vérifié'),
      ChecklistItem(action: 'Heure bloc', status: 'notée'),
    ]),
    ChecklistSection(title: 'DÉBUT DU ROULAGE', items: [
      ChecklistItem(action: 'Phares', status: 'ON'),
      ChecklistItem(action: 'Frein de parc', status: 'desserré'),
      ChecklistItem(action: 'Freins', status: 'essayés et symétriques', color: Colors.orange),
      ChecklistItem(action: 'Gyroscopes et bille', status: 'vérifiés'),
      ChecklistItem(action: 'ATTENTION', status: 'Éviter de dépasser 1200 tr/min tant que la T° huile est en zone jaune', isCheckable: false, color: Colors.orange),
    ]),
    ChecklistSection(title: 'POINT FIXE', items: [
      ChecklistItem(action: 'Frein de parc', status: 'serré'),
      ChecklistItem(action: 'Pression et température d’huile', status: 'plage verte'),
      ChecklistItem(action: 'Pression d’essence', status: 'plage verte'),
      ChecklistItem(action: 'Mixture', status: 'plein riche (vers le haut)'),
      ChecklistItem(action: 'Réchauffage carburateur', status: 'froid (pousser)'),
      ChecklistItem(action: 'Vérification magnétos (2000 tr/min)', status: 'Chute max 175, écart max 50'),
      ChecklistItem(action: 'Réchauffage carburateur', status: 'chaud (tirer) -> Chute ~100 tr/min'),
      ChecklistItem(action: 'Vérification mixture', status: 'Appauvrir -> Chute -> Plein riche'),
      ChecklistItem(action: 'Vérification ralenti', status: '500 à 800 tr/min'),
      ChecklistItem(action: 'Gaz', status: '1200 tr/min'),
    ]),
    ChecklistSection(title: 'AVANT DÉCOLLAGE', items: [
      ChecklistItem(action: 'Commandes', status: 'libres', color: Colors.red),
      ChecklistItem(action: 'Sélecteur magnétos', status: 'L+R (Both)', color: Colors.red),
      ChecklistItem(action: 'Cabine (sièges, ceintures)', status: 'vérifiée'),
      ChecklistItem(action: 'Verrière', status: 'fermée, verrouillée', color: Colors.red),
      ChecklistItem(action: 'Robinet essence (plus plein)', status: 'ouvert', color: Colors.red),
      ChecklistItem(action: 'Pompe électrique', status: 'ON'),
      ChecklistItem(action: 'Trim de profondeur', status: 'position décollage', color: Colors.red),
      ChecklistItem(action: 'Instruments moteur', status: 'plages vertes'),
      ChecklistItem(action: 'Volets', status: 'plein sortis, puis 1er cran', color: Colors.orange),
      ChecklistItem(action: 'Conservateur de cap', status: 'réglé'),
      ChecklistItem(action: 'Transpondeur', status: 'ALT'),
      ChecklistItem(action: 'Voyants alarmes', status: 'éteints'),
    ]),
    ChecklistSection(title: 'BRIEFING AVANT DÉCOLLAGE', items: [
      ChecklistItem(action: 'Rotation', status: '100 km/h (54 kt)', isCheckable: false),
      ChecklistItem(action: 'Pannes', status: 'avant rot: réduit / mineure: TDP / majeure: 150 km/h devant', isCheckable: false, color: Colors.red),
      ChecklistItem(action: 'Confirmer briefing', status: 'Fait'),
    ]),
    ChecklistSection(title: 'APRÈS ATTERRISSAGE', items: [
      ChecklistItem(action: 'Pompe électrique', status: 'OFF'),
      ChecklistItem(action: 'Volets', status: 'rentrés'),
      ChecklistItem(action: 'Transpondeur', status: 'GND'),
    ]),
    ChecklistSection(title: 'ARRÊT MOTEUR', items: [
      ChecklistItem(action: 'Frein de parc', status: 'serré'),
      ChecklistItem(action: 'Radio MASTER', status: 'OFF'),
      ChecklistItem(action: 'Phares et feux de nav', status: 'OFF (sauf anti-col)'),
      ChecklistItem(action: 'Essai coupure au ralenti', status: 'vérifié'),
      ChecklistItem(action: 'Régime', status: '1000 tr/min'),
      ChecklistItem(action: 'Mixture', status: 'étouffoir (bas)', color: Colors.red),
      ChecklistItem(action: 'Magnétos / Clés', status: 'OFF / retirées', color: Colors.red),
      ChecklistItem(action: 'Alternateur / Batterie', status: 'OFF'),
      ChecklistItem(action: 'Horamètre / Heure bloc', status: 'notés'),
      ChecklistItem(action: 'Volets', status: 'Sortis (2e cran)'),
      ChecklistItem(action: 'Frein de parc', status: 'desserré (si possible)'),
    ]),
  ],
};
